blueprint:
  name: Offline Devices
  description: Check 'last_seen' in name and 'timestamp' device_class
    ('last seen' Z2M sensors) to detect offline and if so execute an action.
  domain: automation
  input:
    duration:
      name: Duration
      description: Set Hours, Minutes, or both. Sensors not seen within this duration are considered offline. 
      selector:
        section:
          collapsible: true
          icon: mdi:timer-sand
      inputs:
        hours:
          name: Hours
          description: Set the hours for 'not seen'.
          icon: mdi:clock-outline
          selector:
            number:
              min: 1.0
              max: 24.0
              unit_of_measurement: h
              mode: slider
              step: 1.0
        minutes:
          name: Minutes
          description: Set the minutes for 'not seen'.
          icon: mdi:timer
          selector:
            number:
              min: 0.0
              max: 59.0
              unit_of_measurement: min
              mode: slider
              step: 1.0
    exclude:
      name: Excluded Sensors
      description: "'last seen' sensors (from devices that you want to exclude) to
        exclude from detection. Only entities with 'last seen' in name and 'timestamp'
        in device_class are supported, devices must be expanded!"
      default:
        entity_id: []
      selector:
        target:
          entity:
            domain: sensor
    actions:
      name: Actions
      description: Notifications or similar to be run. {{sensors}} is replaced with
        the names of sensors being offline.
      selector:
        action: {}
  source_url: https://github.com/neyzm/ha-blueprints/offline-devices.yaml

variables:
  day: !input 'schedule.day'
  hours: !input 'schedule.hours'
  exclude: !input 'exclude'
  sensors: "{% set result = namespace(sensors=[]) %}\
    {% for state in states.sensor | rejectattr('attributes.device_class', 'undefined') | selectattr('attributes.device_class', '==', 'timestamp') %}\
      {% if 'last_seen' in state.entity_id and not state.entity_id in exclude.entity_id and (states(state.entity_id) == 'unavailable' or ((as_timestamp(now()) - as_timestamp(states(state.entity_id))) > ((hours | int) * 60 * 60))) %}\
        {% set clean_name = (state.name | regex_replace(find=' last seen', replace='', ignorecase=True) | trim) %}\
        {% set diff = (as_timestamp(now()) - as_timestamp(states(state.entity_id))) | int %}\
        {% if diff < 60 %}\
          {% set last_seen = 'now' %}\
        {% elif diff < 3600 %}\
          {% set last_seen = ((diff / 60) | int) ~ 'min' %}\
        {% elif diff < 86400 %}\
          {% set last_seen = ((diff / 3600) | int) ~ 'hrs' %}\
        {% else %}\
          {% set last_seen = ((diff / 86400) | int) ~ 'd' %}\
        {% endif %}\
        {% set result.sensors = result.sensors + [clean_name ~ ' (' ~ last_seen ~ ')'] %}\
      {% endif %}\
    {% endfor %}\
    {{ result.sensors | join(', ') }}"

trigger:
  - platform: time
    at: !input 'time'

condition:
  - '{{ sensors != "" and (day | int == 0 or day | int == now().isoweekday()) }}'

action:
  - choose: []
    default: !input 'actions'

mode: single