blueprint:
  name: Offline Devices
  description: >
    Detect offline devices using 'last_seen'/'timestamp' (Z2M).
    **Version: v1.1**
  domain: automation
  input:
    duration:
      name: Duration
      description: Set Hours, Minutes, or both. Sensors not seen within this duration are considered offline. 
      selector:
        section:
          collapsible: true
          icon: mdi:timer-sand
      inputs:
        hours:
          name: Hours
          description: Set the hours for 'not seen'.
          icon: mdi:clock-outline
          selector:
            number:
              min: 1.0
              max: 24.0
              unit_of_measurement: h
              mode: slider
              step: 1.0
        minutes:
          name: Minutes
          description: Set the minutes for 'not seen'.
          icon: mdi:timer
          selector:
            number:
              min: 0.0
              max: 59.0
              unit_of_measurement: min
              mode: slider
              step: 1.0
    schedule:
      name: Schedule
      description: Set time and day the test should run.
      icon: mdi:calendar-clock
      selector:
        section:
          collapsible: true
      inputs:
        time:
          name: Time
          description: Input time
          icon: mdi:clock
          default: '10:00:00'
          selector:
            time: {}
        day:
          name: Day
          description: Set a specific day or run everyday.
          icon: mdi:calendar
          default: 0
          selector:
            select:
              options:
                - value: 0
                  label: Everyday
                - value: 1
                  label: Monday
                - value: 2
                  label: Tuesday
                - value: 3
                  label: Wednesday
                - value: 4
                  label: Thursday
                - value: 5
                  label: Friday
                - value: 6
                  label: Saturday
                - value: 7
                  label: Sunday
    exclude:
      name: Excluded Sensors
      description: Choose sensors with `last_seen` or `timestamp` in the name to be excluded from detection.
      icon: mdi:cancel
      default:
        entity_id: []
      selector:
        target:
          entity:
            domain: sensor
    actions:
      name: Actions
      description: Use Actions to create notifications. Use `{{sensors}}` to output the offline devices.
      icon: mdi:code-braces
      selector:
        action: {}

variables:
  day: !input 'schedule.day'
  hours: !input 'duration.hours'
  minutes: !input 'duration.minutes'
  exclude: !input 'exclude'
  sensors: "{% set result = namespace(sensors=[]) %}\
    {% for state in states.sensor | rejectattr('attributes.device_class', 'undefined') | selectattr('attributes.device_class', '==', 'timestamp') %}\
      {% if 'last_seen' in state.entity_id and not state.entity_id in exclude.entity_id and (states(state.entity_id) == 'unavailable' or ((as_timestamp(now()) - as_timestamp(states(state.entity_id))) > (((hours | int) * 3600) + ((minutes | int) * 60)))) %}\
        {% set clean_name = (state.name | regex_replace(find=' last seen', replace='', ignorecase=True) | trim) %}\
        {% set diff = (as_timestamp(now()) - as_timestamp(states(state.entity_id))) | int %}\
        {% if diff < 60 %}\
          {% set last_seen = 'now' %}\
        {% elif diff < 3600 %}\
          {% set last_seen = ((diff / 60) | int) ~ 'min' %}\
        {% elif diff < 86400 %}\
          {% set last_seen = ((diff / 3600) | int) ~ 'hrs' %}\
        {% else %}\
          {% set last_seen = ((diff / 86400) | int) ~ 'd' %}\
        {% endif %}\
        {% set result.sensors = result.sensors + [clean_name ~ ' (' ~ last_seen ~ ')'] %}\
      {% endif %}\
    {% endfor %}\
    {{ result.sensors | join(', ') }}"

trigger:
  - platform: time
    at: !input 'schedule.time'

condition:
  - '{{ sensors != "" and (day | int == 0 or day | int == now().isoweekday()) }}'

action:
  - choose: []
    default: !input 'actions'

mode: single